#!/usr/bin/env python2.5
#
# Plot probability distribution generated by entro.py
# Kornilios Kourtis <kkourt@cslab.ece.ntua.gr>
#
import Gnuplot as G
from random import randint, sample

from entro import e2pd_initial_pd, entropy2pd
import sys

def rand_graph(entropy, fname, graphs_nr=40):
	en = entropy
	_g = G.Gnuplot()
	print 'Entropy', en
	_g("set logscale y")
	_g("set style data linespoints")
	_g('set terminal png size 640 480')

	_initial = ("min", "max")
	pd = []
	for i in xrange(graphs_nr):
		print i, " ",
		sys.stdout.flush()
		pdi = e2pd_initial_pd(256,shuffle=randint(0,256*2),initial=sample(_initial, 1)[0])
		pd.append(G.Data(entropy2pd(en, 256, pdi)))
	print
	_g("set output \'%s\'" % fname)
	_g.plot(*pd)

if __name__ == '__main__':
	from sys import argv, exit
	if len(argv) < 3:
		print "Usage: %s <entropy> <fname> " % argv[0]
		exit(1)
	rand_graph(float(argv[1]), argv[2])
